"""empty message

Revision ID: 31f5a9837529
Revises: 
Create Date: 2026-03-19 00:23:20.334427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31f5a9837529'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('llm_model_id', sa.UUID(), nullable=False),
    sa.Column('llm_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('last_updated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('llm_model_id'),
    sa.UniqueConstraint('llm_name')
    )
    op.create_table('sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'FILE_UPLOAD', 'CSV', 'PDF', name='source_type_enum'), nullable=False),
    sa.Column('source_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ERROR', name='source_status_enum'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('last_updated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('PRODUCT', 'FAQ', 'POLICY', 'ARTICLE', 'RAW_TEXT', name='document_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='document_status_enum'), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('total_chunk_counts', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('last_updated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('idx_documents_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('idx_documents_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('idx_documents_metadata', 'documents', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_source_id', 'documents', ['source_id'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('character_start', sa.Integer(), nullable=True),
    sa.Column('character_end', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('last_updated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('idx_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_index('idx_chunks_metadata', 'chunks', ['metadata'], unique=False, postgresql_using='gin')
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'CHUNKING', 'EMBEDDING', 'DONE', 'FAILED', name='job_status_enum'), nullable=False),
    sa.Column('chunks_total', sa.Integer(), nullable=False),
    sa.Column('chunks_done', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('last_updated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('embeddings',
    sa.Column('embedding_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('llm_model_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('last_updated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.llm_model_id'], ),
    sa.PrimaryKeyConstraint('embedding_id'),
    sa.UniqueConstraint('chunk_id', 'llm_model_id', name='uq_embedding_chunk_model')
    )
    op.create_index('idx_embeddings_llm_model_id', 'embeddings', ['llm_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_embeddings_llm_model_id', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_chunks_metadata', table_name='chunks', postgresql_using='gin')
    op.drop_index('idx_chunks_document_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_source_id', table_name='documents')
    op.drop_index('idx_documents_metadata', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_hash', table_name='documents')
    op.drop_index('idx_documents_document_type', table_name='documents')
    op.drop_table('documents')
    op.drop_table('sources')
    op.drop_table('llm_models')
    # ### end Alembic commands ###
