export enum FsmState {
  IDLE = 'IDLE',
  CART_BUILDING = 'CART_BUILDING',
  AWAITING_ADDRESS = 'AWAITING_ADDRESS',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  AWAITING_CONFIRM = 'AWAITING_CONFIRM',
  PLACING = 'PLACING',
  COMPLETE = 'COMPLETE',
}

export const FSM_TRANSITIONS: Record<FsmState, FsmState | null> = {
  [FsmState.IDLE]: FsmState.CART_BUILDING,
  [FsmState.CART_BUILDING]: FsmState.AWAITING_ADDRESS,
  [FsmState.AWAITING_ADDRESS]: FsmState.AWAITING_PAYMENT,
  [FsmState.AWAITING_PAYMENT]: FsmState.AWAITING_CONFIRM,
  [FsmState.AWAITING_CONFIRM]: FsmState.PLACING,
  [FsmState.PLACING]: FsmState.COMPLETE,
  [FsmState.COMPLETE]: null,
};
